sigma_mapping = {
    'sysmon': 'Microsoft-Windows-Sysmon/Operational',
    'security': 'Security',
    'system': 'System',
    'product': 'platform',
    'windows': 'Windows',
    'linux': 'Linux',
    'linux': 'Unix',
    'sql': 'SQL',
    'django': 'Django',
    'python': 'Python',
    'service': 'channel',
    'vsftpd': 'vsftpd.log',
    'clamav': 'ClamAV',
    'auth': 'auth.log',
    'firewall': 'Firewall',
    'ruby_on_rails': 'Ruby on Rails',
    'spring': 'Spring',
    'dns': 'DNS',
    'dns-server': 'DNS Server',
    'taskscheduler': 'Microsoft-Windows-TaskScheduler/Operational',
    'wmi': 'Microsoft-Windows-WMI-Activity/Operational',
    'driver-framework': 'Microsoft-Windows-DriverFrameworks-UserMode/Operational',
    'dhcp': 'Microsoft-Windows-DHCP-Server/Operational',
    'powershell': 'Microsoft-Windows-PowerShell/Operational',
    'powershell-classic': 'Windows PowerShell',
    'ntlm': 'Microsoft-Windows-NTLM/Operational',
    'dns-server-audit': 'Microsoft-Windows-DNS-Server/Audit',
    'proxy': 'Proxy',
    'apache': 'Apache',
    'webserver': 'Web Server',
}
